module.exports = {
  adjectives: [
    'Defiant ',
    'Homeless ',
    'Adorable ',
    'Delightful',
    'Homely ',
    'Quant ',
    'Adventurous ',
    'Depressed ',
    'Horrible ',
    'Aggressive ',
    'Determined ',
    'Hungry ',
    'Real ',
    'Agreeable ',
    'Different ',
    'Hurt ',
    'Relieved ',
    'Alert ',
    'Difficult ',
    'Repulsive ',
    'Alive ',
    'Disgusted ',
    'Ill ',
    'Rich ',
    'Amused ',
    'Distinct ',
    'Important',
    'Angry ',
    'Disturbed ',
    'Impossible ',
    'Scary',
    'Annoyed ',
    'Dizzy ',
    'Inexpensive ',
    'Selfish',
    'Annoying ',
    'Doubtful ',
    'Innocent ',
    'Shiny ',
    'Anxious ',
    'Drab ',
    'Inquisitive ',
    'Shy ',
    'Arrogant ',
    'Dull ',
    'Itchy ',
    'Silly ',
    'Ashamed ',
    'Sleepy',
    'Attractive ',
    'Eager ',
    'Jealous ',
    'Smiling ',
    'Average ',
    'Easy ',
    'Jittery ',
    'Smoggy ',
    'Awful ',
    'Elated ',
    'Jolly ',
    'Sore ',
    'Elegant ',
    'Joyous ',
    'Sparkling ',
    'Bad ',
    'Embarrassed ',
    'Splendid ',
    'Beautiful ',
    'Enchanting ',
    'Kind ',
    'Spotless ',
    'Better ',
    'Encouraging ',
    'Stormy ',
    'Bewildered ',
    'Energetic ',
    'Lazy ',
    'Strange ',
    'Black ',
    'Enthusiastic ',
    'Light ',
    'Stupid ',
    'Bloody ',
    'Envious ',
    'Lively ',
    'Successful ',
    'Blue ',
    'Evil ',
    'Lonely ',
    'Super ',
    'Blue-eyed ',
    'Excited ',
    'Long ',
    'Blushing ',
    'Expensive ',
    'Lovely ',
    'Talented ',
    'Bored ',
    'Exuberant ',
    'Lucky ',
    'Tame ',
    'Brainy ',
    'Tender ',
    'Brave ',
    'Fair ',
    'Magificent ',
    'Tense ',
    'Breakable ',
    'Faithful ',
    'Misty ',
    'Terrible ',
    'Bright ',
    'Famous ',
    'Modern ',
    'Tasty ',
    'Busy ',
    'Fancy ',
    'Motionless ',
    'Thankful ',
    'Fantastic ',
    'Muddy ',
    'Thoughtful ',
    'Calm ',
    'Fierce ',
    'Mushy ',
    'Thoughtless ',
    'Careful ',
    'Filthy ',
    'Mysterious ',
    'Tired ',
    'Cautious ',
    'Fine ',
    'Tough ',
    'Charming ',
    'Foolish ',
    'Nasty ',
    'Troubled ',
    'Cheerful ',
    'Fragile ',
    'Naughty ',
    'Clean ',
    'Frail ',
    'Nervous ',
    'Ugliest ',
    'Clear ',
    'Frantic ',
    'Nice ',
    'Ugly ',
    'Clever ',
    'Friendly ',
    'Nutty ',
    'Uninterested ',
    'Cloudy ',
    'Frightened ',
    'Unsightly ',
    'Clumsy ',
    'Funny ',
    'Obedient ',
    'Unusual ',
    'Colorful ',
    'Obnoxious ',
    'Upset ',
    'Combative ',
    'Gentle ',
    'Odd ',
    'Uptight ',
    'Comfortable ',
    'Gifted ',
    'Old-fashioned ',
    'Concerned ',
    'Glamorous ',
    'Open ',
    'Vast ',
    'Condemned ',
    'Gleaming ',
    'Outrageous ',
    'Victorious ',
    'Confused ',
    'Glorious ',
    'Outstanding ',
    'Vivacious ',
    'Cooperative ',
    'Good ',
    'Courageous ',
    'Gorgeous ',
    'Panicky ',
    'Wandering ',
    'Crazy ',
    'Graceful ',
    'Perfect ',
    'Weary ',
    'Creepy ',
    'Grieving ',
    'Plain ',
    'Wicked ',
    'Crowded ',
    'Grotesque ',
    'Pleasant ',
    'Wide-Eyed ',
    'Cruel ',
    'Grumpy ',
    'Poised ',
    'Wild ',
    'Curious ',
    'Poor ',
    'Witty ',
    'Cute ',
    'Handsome ',
    'Powerful ',
    'Worrisome ',
    'Happy ',
    'Precious ',
    'Worried ',
    'Dangerous ',
    'Healthy ',
    'Prickly ',
    'Wrong ',
    'Dark ',
    'Helpful ',
    'Proud ',
    'Dead ',
    'Helpless ',
    'Puzzled ',
    'Zany ',
    'Defeated ',
    'Hilarious ',
    'Zealous '
  ],
  nouns: [
    'Laborer',
    'Quiver',
    'Yam',
    'Fish',
    'Spoon',
    'Competition',
    'Pan',
    'Comparison',
    'House',
    'Design',
    'Oil',
    'Force',
    'Fact',
    'Pen',
    'Invention',
    'Afterthought',
    'Cause',
    'Planes',
    'Country',
    'Desk',
    'Distance',
    'Dress',
    'Trucks',
    'Error',
    'Change',
    'Earthquake',
    'Spark',
    'Bear',
    'Stick',
    'Dinosaurs',
    'Use',
    'Authority',
    'Riddle',
    'Passenger',
    'Fowl',
    'Holiday',
    'Bridge',
    'Yard',
    'Camera',
    'Need',
    'Smile',
    'Heat',
    'Walk',
    'Night',
    'Muscle',
    'Plane',
    'Yak',
    'Ball',
    'Yarn',
    'Representative',
    'Shape',
    'Page',
    'Advertisement',
    'Zephyr',
    'Writing',
    'Truck',
    'Example',
    'Team',
    'Crook',
    'Head',
    'Swing',
    'Table',
    'Library',
    'Temper',
    'Cannon',
    'Sister',
    'Babies',
    'Monkey',
    'Cats',
    'Range',
    'Fold',
    'Shoe',
    'Pull',
    'Chance',
    'Weight',
    'Addition',
    'Interest',
    'Nose',
    'Basin',
    'Uncle',
    'Friction',
    'Thread',
    'Bottle',
    'Volcano',
    'Mass',
    'Bone',
    'Vein',
    'Ray',
    'Jail',
    'Destruction',
    'Digestion',
    'Scent',
    'Place',
    'Island',
    'Creator',
    'Seashore',
    'Legs',
    'Button',
    'Bite',
    'Number',
    'Kettle',
    'Punishment',
    'Cloth',
    'Bead',
    'Acoustics',
    'Cushion',
    'Arm',
    'Baseball',
    'Crow',
    'Things',
    'Limit',
    'Locket',
    'Rings',
    'Linen',
    'Friends',
    'Touch',
    'Action',
    'Steam',
    'Jelly',
    'Moon',
    'Lock',
    'Powder',
    'Wren',
    'Tax',
    'Weather',
    'Men',
    'Fire',
    'Sugar',
    'Dirt',
    'Pancake',
    'Sleet',
    'Detail',
    'Bath',
    'Play',
    'Parcel',
    'Toy',
    'Rainstorm',
    'Degree',
    'Zinc',
    'Aunt',
    'Finger',
    'Nation',
    'Calendar',
    'Cellar',
    'Thought',
    'Watch',
    'Flowers',
    'Fruit',
    'Stem',
    'Fireman',
    'River',
    'School',
    'Rifle',
    'Meal',
    'Motion',
    'Pie',
    'Coal',
    'Base',
    'Plant',
    'Frogs',
    'Laugh',
    'Balance',
    'Toothpaste',
    'Door',
    'Match',
    'Selection',
    'Plants',
    'Wrist',
    'Act',
    'Rock',
    'Plastic',
    'Ducks',
    'Bat',
    'Wish',
    'Mist',
    'Breath',
    'Level',
    'Bee',
    'Increase',
    'Part',
    'Noise',
    'Theory',
    'Person',
    'Notebook',
    'Chin',
    'Thing',
    'Quarter',
    'Tramp',
    'Talk',
    'Food',
    'Wind',
    'Neck',
    'Plate',
    'Coat',
    'Judge',
    'Birth',
    'Scarf',
    'Whip',
    'Wrench',
    'Children',
    'Paper',
    'Coast',
    'Silk',
    'Wine',
    'Impulse',
    'Trousers',
    'Belief',
    'Committee',
    'Condition',
    'Cream',
    'Teeth',
    'Gorilla',
    'Key',
    'Hole',
    'Health',
    'Cobweb',
    'Form',
    'Maid',
    'Work',
    'Knowledge',
    'Afternoon',
    'Boy',
    'Peace',
    'Writer',
    'Memory',
    'Baby',
    'Train',
    'Position',
    'Offer',
    'Stomach',
    'Business',
    'screw',
    'Wash',
    'Copper',
    'Hose',
    'Bushes',
    'Fly',
    'Sink',
    'Store',
    'Rest',
    'Grandfather',
    'Snails',
    'Crib',
    'Snake',
    'Popcorn',
    'Cave',
    'Pets',
    'Partner',
    'Quartz',
    'Stocking',
    'Ocean',
    'Collar',
    'Skate',
    'Nerve',
    'Verse',
    'Street',
    'Cast',
    'Cattle',
    'Month',
    'Lace',
    'Cars',
    'Snow',
    'Front',
    'Machine',
    'Suit',
    'Pocket',
    'Insect',
    'Mind',
    'Air',
    'Drawer',
    'Soup',
    'Sheep',
    'Attraction',
    'Seat',
    'Brake',
    'Crown',
    'Alarm',
    'Jeans',
    'Snail',
    'Hands',
    'Humor',
    'Aftermath',
    'Rabbit',
    'Grandmother',
    'Yoke',
    'Nut',
    'Payment',
    'Tendency',
    'Twig',
    'Playground',
    'Surprise',
    'Arch',
    'Flame',
    'Doll',
    'Home',
    'Observation',
    'Support',
    'Name',
    'Rose',
    'Winter'
  ],
  genre: [
    'Electronic',
    'Rock',
    'Jazz',
    'Dubstep',
    'Rhythm and Blues',
    'Techno',
    'Country',
    'Electro',
    'Indie',
    'Pop',
  ],
  albumLeads: [
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'Songs About',
    'My Time at',
    'Living with',
    'Have You Seen',
    'What is',
    'All You Need Is',
    'No',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    "Don''t Stop",
    "Crying About",
    "Let''s Talk About",
    "Dreaming of",
    "Thinking of",
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ]
}